add_newline = false

format = """
${custom.tmux_session}\
$battery\
$python\
$directory\
$username\
$hostname\
$shlvl\
$git_branch\
$git_status\
$memory_usage\
$env_var\
$sudo\
$jobs\
$status\
$shell\
$character
"""

# right_format = "${custom.tmux_session}"

[custom.tmux_session]
# command = "tmux display-message -p '#S' 2>/dev/null"
# command = "tmux display-message -p '#S' | sed 's|'$(basename \"$PWD\" | tr '.' '_')'||'"
when = "test $(tmux list-sessions | wc -l) -gt 0"
style = "bold grey"
symbol = "î¯ˆ "
format = "[$symbol]($style)"

[character]
success_symbol="[â¯](green)" #ï„…ïƒšï™ï‘ ï”ï‘ ï™ï˜½ï”ïï‹ï™ï¤‰ï‘ ï‘Šî‚°î‚±î‚´î‚µî˜‚îîîî‘î’î˜â¦’â€ºâ–·â–¶â¼ºâ–¹â™˜â¤âŸ©âŸ«â¦Šâ¦’â¼Š

[directory]
format = "[$path]($style)[$lock_symbol]($lock_style) "
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = false
style = "green"
repo_root_style = "bright-green"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold yellow dimmed"

[git_status]
up_to_date = "âœ“" #âœ“
style = "bold yellow dimmed"
format = "[$all_status$ahead_behind]($style) "

[python]
format = '[Python ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
# style = "bold green"

# [jobs]
# symbol = "ï€…"
# style = "bold white dimmed"

# [status]
# disabled = false
# style = "red"

# [battery]
# full_symbol = "ğŸ”‹"
# charging_symbol = "ğŸ”Œ"
# discharging_symbol = "âš¡"

# [[battery.display]]
# threshold = 30
# style = "bold red"

# [git_commit]
# commit_hash_length = 8
# style = "bold white"

# [git_state]
# format = '[\($state( $progress_current of $progress_total)\)]($style) '

# [hostname]
# ssh_only = false
# format = "<[$hostname]($style)>"
# trim_at = "-"
# style = "bold dimmed white"
# disabled = true


# [memory_usage]
# format = "$symbol[${ram}( | ${swap})]($style) "
# threshold = 70
# style = "bold dimmed white"
# disabled = false

# [package]
# disabled = true

# [rust]
# format = "[$symbol$version]($style) "
# style = "bold green"

# [time]
# time_format = "%T"
# format = "ğŸ•™ $time($style) "
# style = "bright-white"
# disabled = false

# [username]
# style_user = "bold dimmed blue"
# show_always = false
